default:
  module: "src.server.tasks.locomo.Locomo9Task"
  parameters:
    name: "locomo-9"
    data_file: "data/locomo/locomo9.json"
    llm_judge_agent: "Pro/Qwen/Qwen2.5-7B-Instruct"  # 从 configs/llmapi/evaluate_agent.yaml 中选择 agent

locomo-9:
  parameters:
    name: "locomo-9"
    data_file: "data/locomo/locomo9.json"
    llm_judge_agent: "Pro/Qwen/Qwen2.5-7B-Instruct"  # 从 configs/llmapi/evaluate_agent.yaml 中选择 agent

