default:
  module: "src.server.tasks.locomo.Locomo3Task"
  parameters:
    name: "locomo-3"
    data_file: "data/locomo/locomo3.json"
    llm_judge_agent: "Pro/Qwen/Qwen2.5-7B-Instruct"  # 从 configs/llmapi/evaluate_agent.yaml 中选择 agent

locomo-3:
  parameters:
    name: "locomo-3"
    data_file: "data/locomo/locomo3.json"
    llm_judge_agent: "Pro/Qwen/Qwen2.5-7B-Instruct"  # 从 configs/llmapi/evaluate_agent.yaml 中选择 agent

