default:
  module: "src.server.tasks.locomo.Locomo5Task"
  parameters:
    name: "locomo-5"
    data_file: "data/locomo/locomo5.json"
    llm_judge_agent: "Pro/Qwen/Qwen2.5-7B-Instruct"  # 从 configs/llmapi/evaluate_agent.yaml 中选择 agent

locomo-5:
  parameters:
    name: "locomo-5"
    data_file: "data/locomo/locomo5.json"
    llm_judge_agent: "Pro/Qwen/Qwen2.5-7B-Instruct"  # 从 configs/llmapi/evaluate_agent.yaml 中选择 agent

