default:
  module: "src.server.tasks.locomo.Locomo1Task"
  parameters:
    name: "locomo-1"
    data_file: "data/locomo/locomo1.json"
    llm_judge_agent: "Pro/Qwen/Qwen2.5-7B-Instruct"  # 从 configs/llmapi/evaluate_agent.yaml 中选择 agent

locomo-1:
  parameters:
    name: "locomo-1"
    data_file: "data/locomo/locomo1.json"
    llm_judge_agent: "Pro/Qwen/Qwen2.5-7B-Instruct"  # 从 configs/llmapi/evaluate_agent.yaml 中选择 agent

