default:
  module: "src.server.tasks.locomo.Locomo4Task"
  parameters:
    name: "locomo-4"
    data_file: "data/locomo/locomo4.json"
    llm_judge_agent: "Pro/Qwen/Qwen2.5-7B-Instruct"  # 从 configs/llmapi/evaluate_agent.yaml 中选择 agent

locomo-4:
  parameters:
    name: "locomo-4"
    data_file: "data/locomo/locomo4.json"
    llm_judge_agent: "Pro/Qwen/Qwen2.5-7B-Instruct"  # 从 configs/llmapi/evaluate_agent.yaml 中选择 agent

